mood_tags = [
  "action", "adventure", "advertising", "background", "ballad", "calm",
  "children", "christmas", "commercial", "cool", "corporate",
  "dark", "deep", "documentary", "drama", "dramatic",
  "dream", "emotional", "energetic", "epic", "fast",
  "film", "fun", "funny", "game", "groovy",
  "happy", "heavy", "holiday", "hopeful", "inspiring",
  "love", "meditative", "melancholic", "melodic", "motivational",
  "movie", "nature", "party", "positive", "powerful",
  "relaxing", "retro", "romantic", "sad", "sexy",
  "slow", "soft", "soundscape", "space", "sport",
  "summer", "trailer", "travel", "upbeat", "uplifting"
]

genre_tags = [
    "60s", "70s", "80s", "90s", "acidjazz", "alternative", "alternativerock", "ambient", "atmospheric", "blues", 
    "bluesrock", "bossanova", "breakbeat", "celtic", "chanson", "chillout", "choir", "classical", "classicrock", 
    "club", "contemporary", "country", "dance", "darkambient", "darkwave", "deephouse", "disco", "downtempo", 
    "drumnbass", "dub", "dubstep", "easylistening", "edm", "electronic", "electronica", "electropop", "ethno", 
    "eurodance", "experimental", "folk", "funk", "fusion", "groove", "grunge", "hard", "hardrock", "hiphop", 
    "house", "idm", "improvisation", "indie", "industrial", "instrumentalpop", "instrumentalrock", "jazz", 
    "jazzfusion", "latin", "lounge", "medieval", "metal", "minimal", "newage", "newwave", "orchestral", "pop", 
    "popfolk", "poprock", "postrock", "progressive", "psychedelic", "punkrock", "rap", "reggae", "rnb", "rock", 
    "rocknroll", "singersongwriter", "soul", "soundtrack", "swing", "symphonic", "synthpop", "techno", "trance", 
    "triphop", "world", "worldfusion"
]

mood_synonyms = {
            "action": ["intense", "thrilling", "dynamic", "explosive", "pumping"],
            "adventure": ["exploratory", "journey", "quest", "expedition", "voyage"],
            "advertising": ["promotional", "catchy", "jingle", "branded", "commercial"],
            "background": ["ambient", "subtle", "unobtrusive", "atmospheric", "underscore"],
            "ballad": ["storytelling", "narrative", "emotional", "heartfelt", "intimate"],
            "calm": ["peaceful", "serene", "tranquil", "soothing", "gentle"],
            "children": ["playful", "whimsical", "innocent", "youthful", "fun"],
            "christmas": ["festive", "holiday", "cheerful", "jolly", "wintry"],
            "commercial": ["catchy", "memorable", "upbeat", "positive", "energetic"],
            "cool": ["chill", "laid-back", "smooth", "relaxed", "mellow"],
            "corporate": ["professional", "polished", "refined", "sleek", "business"],
            "dark": ["brooding", "ominous", "mysterious", "gloomy", "shadowy"],
            "deep": ["profound", "thoughtful", "philosophical", "introspective", "meaningful"],
            "documentary": ["informative", "educational", "factual", "realistic", "authentic"],
            "drama": ["theatrical", "expressive", "passionate", "intense", "serious"],
            "dramatic": ["theatrical", "grand", "powerful", "stirring", "emotive"],
            "dream": ["ethereal", "surreal", "fantastical", "otherworldly", "floaty"],
            "emotional": ["feeling", "sentimental", "expressive", "touching", "moving"],
            "energetic": ["lively", "vibrant", "animated", "spirited", "exuberant"],
            "epic": ["grandiose", "majestic", "heroic", "monumental", "cinematic"],
            "fast": ["rapid", "quick", "speedy", "brisk", "up-tempo"],
            "film": ["cinematic", "soundtrack", "orchestral", "visual", "thematic"],
            "fun": ["playful", "joyful", "lighthearted", "cheerful", "amusing"],
            "funny": ["humorous", "comical", "witty", "silly", "laughable"],
            "game": ["interactive", "playful", "competitive", "immersive", "virtual"],
            "groovy": ["funky", "rhythmic", "danceable", "syncopated", "boogie"],
            "happy": ["joyful", "cheerful", "upbeat", "sunny", "positive"],
            "heavy": ["intense", "powerful", "weighty", "forceful", "aggressive"],
            "holiday": ["festive", "celebratory", "seasonal", "vacation", "cheerful"],
            "hopeful": ["optimistic", "promising", "encouraging", "bright", "positive"],
            "inspiring": ["motivational", "uplifting", "encouraging", "stimulating", "empowering"],
            "love": ["romantic", "affectionate", "passionate", "tender", "intimate"],
            "meditative": ["contemplative", "reflective", "zen", "calm", "peaceful"],
            "melancholic": ["nostalgic", "wistful", "bittersweet", "pensive", "sorrowful"],
            "melodic": ["tuneful", "harmonious", "musical", "lyrical", "catchy"],
            "motivational": ["inspirational", "encouraging", "empowering", "rousing", "stimulating"],
            "movie": ["cinematic", "filmic", "theatrical", "dramatic", "narrative"],
            "nature": ["organic", "natural", "earthy", "outdoors", "environmental"],
            "party": ["festive", "celebratory", "lively", "fun", "social"],
            "positive": ["optimistic", "upbeat", "cheerful", "happy", "bright"],
            "powerful": ["strong", "forceful", "intense", "potent", "dynamic"],
            "relaxing": ["calming", "soothing", "peaceful", "restful", "tranquil"],
            "retro": ["vintage", "nostalgic", "classic", "old-school", "throwback"],
            "romantic": ["loving", "passionate", "intimate", "affectionate", "sentimental"],
            "sad": ["mournful", "sorrowful", "melancholy", "blue", "heartbreaking"],
            "sexy": ["sensual", "seductive", "alluring", "provocative", "flirtatious"],
            "slow": ["leisurely", "unhurried", "measured", "languid", "deliberate"],
            "soft": ["gentle", "quiet", "delicate", "muted", "subtle"],
            "soundscape": ["textural", "environmental", "immersive", "atmospheric", "ambient"],
            "space": ["cosmic", "stellar", "astral", "celestial", "interstellar"],
            "sport": ["athletic", "energetic", "competitive", "dynamic", "active"],
            "summer": ["sunny", "warm", "bright", "carefree", "vacation"],
            "trailer": ["teaser", "promotional", "cinematic", "dramatic", "epic"],
            "travel": ["wanderlust", "exploration", "journey", "adventure", "movement"],
            "upbeat": ["cheerful", "lively", "positive", "energetic", "bouncy"],
            "uplifting": ["inspiring", "encouraging", "heartening", "positive", "elevating"]
        }